website: http://ob-mc.net
name: NametagHide
author: Fahrenheit451
version: 1.0
api-version: "1.21"
main: net.obmc.OBNametagHide.OBNametagHide
description: Hides name tag in worlds listed in the configuration file
commands:
  nametaghide:
    description: NametagHide command.
    usage: Type /nametaghide for a list of commands
    aliases:
      - nth
